[opener]
edit = [
    { run = "nvim %*", block = true, desc = "nvim", for = "windows" },
    { run = "code %*", orphan = true, desc = "code", for = "windows" },
    { run = "start %*", orphan = true, desc = "start", for = "windows" },
]

